import { NextResponse } from "next/server";

export const runtime = "nodejs";

function has(name) {
  const v = process.env[name];
  return v !== undefined && v !== null && String(v).trim() !== "";
}

export async function GET() {
  return NextResponse.json({
    keys: {
      GITHUB_TOKEN: has("GITHUB_TOKEN"),
      SLACK_TOKEN: has("SLACK_TOKEN"),
      STRIPE_SECRET_KEY: has("STRIPE_SECRET_KEY") || has("STRIPE_API_KEY"),
      GOOGLE_ACCESS_TOKEN: has("GOOGLE_ACCESS_TOKEN"),
      MS_GRAPH_ACCESS_TOKEN: has("MS_GRAPH_ACCESS_TOKEN"),
      ATLASSIAN_SITE_URL: has("ATLASSIAN_SITE_URL"),
      ATLASSIAN_EMAIL: has("ATLASSIAN_EMAIL"),
      ATLASSIAN_API_TOKEN: has("ATLASSIAN_API_TOKEN"),
      ATLASSIAN_CLIENT_ID: has("ATLASSIAN_CLIENT_ID"),
      ATLASSIAN_CLIENT_SECRET: has("ATLASSIAN_CLIENT_SECRET"),
      SALESFORCE_INSTANCE_URL: has("SALESFORCE_INSTANCE_URL"),
      SALESFORCE_ACCESS_TOKEN: has("SALESFORCE_ACCESS_TOKEN"),
      MAILCHIMP_API_KEY: has("MAILCHIMP_API_KEY"),
      MAILCHIMP_SERVER_PREFIX: has("MAILCHIMP_SERVER_PREFIX"),
      AIRTABLE_API_KEY: has("AIRTABLE_API_KEY"),
      JOTFORM_API_KEY: has("JOTFORM_API_KEY"),
      TICKETBUD_API_KEY: has("TICKETBUD_API_KEY"),
      DIGISIGN_API_KEY: has("DIGISIGN_API_KEY"),
      DIGISIGN_BASE_URL: has("DIGISIGN_BASE_URL"),
      CLICKUP_CLIENT_ID: has("CLICKUP_CLIENT_ID"),
      CLICKUP_CLIENT_SECRET: has("CLICKUP_CLIENT_SECRET"),
      EVENTBRITE_CLIENT_ID: has("EVENTBRITE_CLIENT_ID"),
      EVENTBRITE_CLIENT_SECRET: has("EVENTBRITE_CLIENT_SECRET"),
      EVENTBRITE_PRIVATE_TOKEN: has("EVENTBRITE_PRIVATE_TOKEN"),
      EVENTBRITE_PUBLIC_TOKEN: has("EVENTBRITE_PUBLIC_TOKEN")
    }
  });
}
