import { NextResponse } from "next/server";

export const runtime = "nodejs";

function has(name) {
  const v = process.env[name];
  return v !== undefined && v !== null && String(v).trim() !== "";
}

export async function GET() {
  return NextResponse.json({
    keys: {
      GITHUB_TOKEN: has("GITHUB_TOKEN"),
      SLACK_TOKEN: has("SLACK_TOKEN"),
      DISCORD_CLIENT_ID: has("DISCORD_CLIENT_ID"),
      DISCORD_CLIENT_SECRET: has("DISCORD_CLIENT_SECRET"),
      STRIPE_SECRET_KEY: has("STRIPE_SECRET_KEY") || has("STRIPE_API_KEY"),
      GOOGLE_ACCESS_TOKEN: has("GOOGLE_ACCESS_TOKEN"),
      MS_GRAPH_ACCESS_TOKEN: has("MS_GRAPH_ACCESS_TOKEN"),
      ATLASSIAN_SITE_URL: has("ATLASSIAN_SITE_URL"),
      ATLASSIAN_EMAIL: has("ATLASSIAN_EMAIL"),
      ATLASSIAN_API_TOKEN: has("ATLASSIAN_API_TOKEN"),
      ATLASSIAN_CLIENT_ID: has("ATLASSIAN_CLIENT_ID"),
      ATLASSIAN_CLIENT_SECRET: has("ATLASSIAN_CLIENT_SECRET"),
      SALESFORCE_INSTANCE_URL: has("SALESFORCE_INSTANCE_URL"),
      SALESFORCE_ACCESS_TOKEN: has("SALESFORCE_ACCESS_TOKEN"),
      ZOHO_CLIENT_ID: has("ZOHO_CLIENT_ID"),
      ZOHO_CLIENT_SECRET: has("ZOHO_CLIENT_SECRET"),
      XERO_CLIENT_ID: has("XERO_CLIENT_ID"),
      XERO_CLIENT_SECRET: has("XERO_CLIENT_SECRET"),
      ZENDESK_CLIENT_ID: has("ZENDESK_CLIENT_ID"),
      ZENDESK_CLIENT_SECRET: has("ZENDESK_CLIENT_SECRET"),
      ZENDESK_SUBDOMAIN: has("ZENDESK_SUBDOMAIN"),
      INTERCOM_CLIENT_ID: has("INTERCOM_CLIENT_ID"),
      INTERCOM_CLIENT_SECRET: has("INTERCOM_CLIENT_SECRET"),
      MONDAY_CLIENT_ID: has("MONDAY_CLIENT_ID"),
      MONDAY_CLIENT_SECRET: has("MONDAY_CLIENT_SECRET"),
      LINEAR_CLIENT_ID: has("LINEAR_CLIENT_ID"),
      LINEAR_CLIENT_SECRET: has("LINEAR_CLIENT_SECRET"),
      TRELLO_CLIENT_ID: has("TRELLO_CLIENT_ID"),
      TRELLO_CLIENT_SECRET: has("TRELLO_CLIENT_SECRET"),
      GITLAB_CLIENT_ID: has("GITLAB_CLIENT_ID"),
      GITLAB_CLIENT_SECRET: has("GITLAB_CLIENT_SECRET"),
      BITBUCKET_CLIENT_ID: has("BITBUCKET_CLIENT_ID"),
      BITBUCKET_CLIENT_SECRET: has("BITBUCKET_CLIENT_SECRET"),
      BIGQUERY_ACCESS_TOKEN: has("GOOGLE_ACCESS_TOKEN"),
      MAILCHIMP_API_KEY: has("MAILCHIMP_API_KEY"),
      MAILCHIMP_SERVER_PREFIX: has("MAILCHIMP_SERVER_PREFIX"),
      AIRTABLE_API_KEY: has("AIRTABLE_API_KEY"),
      JOTFORM_API_KEY: has("JOTFORM_API_KEY"),
      TICKETBUD_API_KEY: has("TICKETBUD_API_KEY"),
      DIGISIGN_API_KEY: has("DIGISIGN_API_KEY"),
      DIGISIGN_BASE_URL: has("DIGISIGN_BASE_URL"),
      CLICKUP_CLIENT_ID: has("CLICKUP_CLIENT_ID"),
      CLICKUP_CLIENT_SECRET: has("CLICKUP_CLIENT_SECRET"),
      EVENTBRITE_CLIENT_ID: has("EVENTBRITE_CLIENT_ID"),
      EVENTBRITE_CLIENT_SECRET: has("EVENTBRITE_CLIENT_SECRET"),
      EVENTBRITE_PRIVATE_TOKEN: has("EVENTBRITE_PRIVATE_TOKEN"),
      EVENTBRITE_PUBLIC_TOKEN: has("EVENTBRITE_PUBLIC_TOKEN"),
      SIGNNOW_CLIENT_ID: has("SIGNNOW_CLIENT_ID"),
      SIGNNOW_CLIENT_SECRET: has("SIGNNOW_CLIENT_SECRET"),
      ADOBE_CLIENT_ID: has("ADOBE_CLIENT_ID"),
      ADOBE_CLIENT_SECRET: has("ADOBE_CLIENT_SECRET"),
      DATABRICKS_API_KEY: has("DATABRICKS_API_KEY"),
      DATABRICKS_WORKSPACE_URL: has("DATABRICKS_WORKSPACE_URL"),
      NOTION_API_KEY: has("NOTION_API_KEY"),
      SUPABASE_URL: has("SUPABASE_URL"),
      SUPABASE_ANON_KEY: has("SUPABASE_ANON_KEY"),
      CODA_API_KEY: has("CODA_API_KEY"),
      GURU_USER_TOKEN: has("GURU_USER_TOKEN"),
      FIREBASE_CLIENT_ID: has("FIREBASE_CLIENT_ID"),
      FIREBASE_CLIENT_SECRET: has("FIREBASE_CLIENT_SECRET")
    }
  });
}
